### ISSUE TITLE
FAILED: Function `-[CMMASActivationManager isAppActivated]` not found.

### ISSUE THREAD

**Issue by mathmart42** [davidepedrazzi/CleanMyMacX#19]
we got this I think the offset code is HS

**Comment by youssef02** [comment]
well, installed fresh install, and got it patched, but still don't have full version

**Comment by davidepedrazzi** [comment]
Any information on this? Intel Chip or Apple Silicon? macOS version? Did you download the app from the App Store or website?

Also what do you mean when you say "we"? We who? "HS"?

@youssef02 Your comment does not seem related to this issue. Open a new one if you need help.

For both: I understand you might have trouble expressing yourself but I'm not a wizard. You have to make an effort if you want to be understood.

**Comment by youssef02** [comment]
Sorry @davidepedrazzi, the problem is to produce this error is to try to patch the software 2 times, the first time running patch work fine, but the second running of the patch.py produce that error, "isAppActivated"  thing,


as for the hardware, I am using a macOS intel-chip 2019, with Ventura v13.2.1 


I think the error is he tried to patch it 2 times. try doing a fresh install, remove the old one, and patch again.

Hope this help

**Comment by davidepedrazzi** [comment]
What you say is correct. As expected, it cannot find the function `isAppActivated` because it has already been patched. Why would someone want to apply the same patch twice, anyway?

In the future, I may consider adding a warning if the app has already been patched.

Thank you for your understanding and help.
